server:
  port: 4222

spring:
  application:
    name: camunda-api-demo

  datasource:
    url: jdbc:postgresql://localhost:5534/ventas_db
    username: postgres17
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  threads:
    virtual:
      enabled: true

camunda:
  client:
    mode: self-managed
    auth:
      method: oidc
      client-id: orchestration
      client-secret: secret
      token-url: http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token
      audience: orchestration-api
    grpc-address: http://localhost:26500
    rest-address: http://localhost:8080
    prefer-rest-over-grpc: false
    request-timeout: PT30S
    request-timeout-offset: PT5S
    worker:
      defaults:
        request-timeout: PT30S
        poll-interval: PT1S
        timeout: PT5M

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics